cleanup writing of tests logfiles
Signed-off-by: BlackEagle <ike.devolder@gmail.com>

diff --git a/tests/test1 b/tests/test1
--- a/tests/test1
+++ b/tests/test1
@@ -19,7 +19,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../par2 v testdata.par > ../$testname.log || { echo "ERROR: Initial PAR 1.0 verification failed" ; exit 1; } >&2
+../../par2 v testdata.par > $tests/$testname.log || { echo "ERROR: Initial PAR 1.0 verification failed" ; exit 1; } >&2
 
 cd ..
 rm -rf run$testname
diff --git a/tests/test17 b/tests/test17
--- a/tests/test17
+++ b/tests/test17
@@ -20,7 +20,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../par2 r recovery.par2 >> ../$testname.log || { echo "ERROR: reparation of files using PAR 2.0 failed" ; exit 1; } >&2
+../../par2 r recovery.par2 > $tests/$testname.log || { echo "ERROR: reparation of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd ..
 rm -rf run$testname
diff --git a/tests/test19 b/tests/test19
--- a/tests/test19
+++ b/tests/test19
@@ -26,7 +26,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../par2 c -s200 -c1 recovery datafile > ../$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+../../par2 c -s200 -c1 recovery datafile > $tests/$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 ls -l
 
 banner="Damaging data file (trim first 100 bytes)"
@@ -48,7 +48,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../par2 r -S99 -vv recovery.par2 > ../$testname.log && { echo "ERROR: Repair should not be possible with skip leaway set to 99" ; exit 1; } >&2
+../../par2 r -S99 -vv recovery.par2 >> $tests/$testname.log && { echo "ERROR: Repair should not be possible with skip leaway set to 99" ; exit 1; } >&2
 ls -l
 
 banner="Repairing using PAR 2.0 data (with skip leaway 100 - should succeed)"
@@ -58,7 +58,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../par2 r -S100 -vv recovery.par2 > ../$testname.log || { echo "ERROR: Repair should be possible with skip leaway set to 100" ; exit 1; } >&2
+../../par2 r -S100 -vv recovery.par2 >> $tests/$testname.log || { echo "ERROR: Repair should be possible with skip leaway set to 100" ; exit 1; } >&2
 ls -l
 
 cd ..
diff --git a/tests/test5 b/tests/test5
--- a/tests/test5
+++ b/tests/test5
@@ -18,7 +18,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../par2 c -r100 -b190 -a newtest test-*.data > ../$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+../../par2 c -r100 -b190 -a newtest test-*.data > $tests/$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 cp test-0.data test-0.data.orig
 cp test-1.data test-1.data.orig
@@ -42,7 +42,7 @@ echo $dashes
 
 rm -f test-*.data
 
-../../par2 r newtest.par2 >> ../$testname.log || { echo "ERROR: Full Repair using PAR 2.0 failed" ; exit 1; } >&2
+../../par2 r newtest.par2 >> $tests/$testname.log || { echo "ERROR: Full Repair using PAR 2.0 failed" ; exit 1; } >&2
 
 cmp -s test-0.data test-0.data.orig && cmp -s test-1.data test-1.data.orig && cmp -s test-2.data test-2.data.orig && cmp -s test-3.data test-3.data.orig && cmp -s test-4.data test-4.data.orig && cmp -s test-5.data test-5.data.orig && cmp -s test-6.data test-6.data.orig && cmp -s test-7.data test-7.data.orig && cmp -s test-8.data test-8.data.orig && cmp -s test-9.data test-9.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1 ; } >&2
 
diff --git a/tests/test8 b/tests/test8
--- a/tests/test8
+++ b/tests/test8
@@ -22,7 +22,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../../par2 c -R testdata.par2 * > ../../$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+../../../par2 c -R testdata.par2 * > $tests/$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd ..
 mv source1 source2
@@ -36,7 +36,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../../par2 v testdata.par2 >> ../../$testname.log || { echo "ERROR: verification of files using PAR 2.0 failed" ; exit 1; } >&2
+../../../par2 v testdata.par2 >> $tests/$testname.log || { echo "ERROR: verification of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd ../..
 rm -rf run$testname
