more "fixing" of tests
In some conditions the folder "tests" does not exist in the right place.
If we skip changing to tests, we must also remove the *.log files since
we no longer have a clue where those will land.

Signed-off-by: BlackEagle <ike.devolder@gmail.com>

diff --git a/tests/test1 b/tests/test1
--- a/tests/test1
+++ b/tests/test1
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -19,8 +18,8 @@ rm -rf "run$testname"
 
 mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $TESTDATA/flatdata.tar.gz 2>&1 >> $TESTROOT/$testname.log || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
-tar -xzf $TESTDATA/flatdata-par1files.tar.gz 2>&1 >> $TESTROOT/$testname.log || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/flatdata.tar.gz 2>&1 || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/flatdata-par1files.tar.gz 2>&1 || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2
 
 banner="Verifying using PAR 1.0 data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -29,7 +28,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 v testdata.par > $TESTROOT/$testname.log || { echo "ERROR: Initial PAR 1.0 verification failed" ; exit 1; } >&2
+$execdir/par2 v testdata.par || { echo "ERROR: Initial PAR 1.0 verification failed" ; exit 1; } >&2
 
 cd $TESTROOT
 rm -rf run$testname
diff --git a/tests/test11 b/tests/test11
--- a/tests/test11
+++ b/tests/test11
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -28,7 +27,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 c -b100 testdata.par2 * > $TESTROOT/$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 c -b100 testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 banner="repair 5% of 100 blocks par2files removing 3 files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -39,7 +38,7 @@ echo $dashes
 
 rm file file1 file3
 
-$execdir/par2 r testdata.par2 * >> $TESTROOT/$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 r testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 banner="repair 5% of 100 blocks par2files removing 1 files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -50,7 +49,7 @@ echo $dashes
 
 rm file5
 
-$execdir/par2 r testdata.par2 * > $TESTROOT/$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 r testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd $TESTROOT
 rm -rf run$testname
diff --git a/tests/test13 b/tests/test13
--- a/tests/test13
+++ b/tests/test13
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -28,7 +27,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 c testdata.par2 *.data > $TESTROOT/$testname.log || { echo "ERROR: creating repair files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 c testdata.par2 *.data || { echo "ERROR: creating repair files using PAR 2.0 failed" ; exit 1; } >&2
 
 banner="repair files where 1 byte got removed at the end of a file"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -40,7 +39,7 @@ echo $dashes
 mv test-1.data test-1.data-correct
 dd if=test-1.data-correct bs=177173 count=1 of=test-1.data
 
-$execdir/par2 r testdata.par2 > $TESTROOT/$testname.log || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 r testdata.par2 || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd $TESTROOT
 rm -rf run$testname
diff --git a/tests/test15 b/tests/test15
--- a/tests/test15
+++ b/tests/test15
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -29,7 +28,7 @@ echo $banner
 echo $dashes
 
 cd par2-0.6.8-crash
-$execdir/par2 r pack-ea5f7f848340980493ed39f5b7173d956c680e43.par2 > $TESTROOT/$testname.log || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 r pack-ea5f7f848340980493ed39f5b7173d956c680e43.par2 || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd $TESTROOT
 rm -rf run$testname
diff --git a/tests/test18 b/tests/test18
--- a/tests/test18
+++ b/tests/test18
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -28,7 +27,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 c recovery flatdata.tar.gz > $TESTROOT/$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$execdir/par2 c recovery flatdata.tar.gz || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 banner="Verifying using PAR 2.0 data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -41,7 +40,7 @@ mv flatdata.tar.gz flatdata.tar.gz-orig
 dd if=flatdata.tar.gz-orig bs=1983 count=1 of=flatdata.tar.gz
 rm -f flatdata.tar.gz-orig
 
-$execdir/par2 r recovery.par2 ./* >> $TESTROOT/$testname.log || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
+$execdir/par2 r recovery.par2 ./* || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
 
 cd $TESTROOT
 rm -rf run$testname
diff --git a/tests/test19 b/tests/test19
--- a/tests/test19
+++ b/tests/test19
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -36,7 +35,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 c -s200 -c1 recovery datafile > $TESTROOT/$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$execdir/par2 c -s200 -c1 recovery datafile || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 ls -l
 
 banner="Damaging data file (trim first 100 bytes)"
@@ -58,7 +57,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 r -N -S99 -vv recovery.par2 >> $TESTROOT/$testname.log && { echo "ERROR: Repair should not be possible with skip leaway set to 99" ; exit 1; } >&2
+$execdir/par2 r -N -S99 -vv recovery.par2 && { echo "ERROR: Repair should not be possible with skip leaway set to 99" ; exit 1; } >&2
 ls -l
 
 banner="Repairing using PAR 2.0 data (with skip leaway 100 - should succeed)"
@@ -68,7 +67,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 r -N -S100 -vv recovery.par2 >> $TESTROOT/$testname.log || { echo "ERROR: Repair should be possible with skip leaway set to 100" ; exit 1; } >&2
+$execdir/par2 r -N -S100 -vv recovery.par2 || { echo "ERROR: Repair should be possible with skip leaway set to 100" ; exit 1; } >&2
 ls -l
 
 cd $TESTROOT
diff --git a/tests/test2 b/tests/test2
--- a/tests/test2
+++ b/tests/test2
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -29,7 +28,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 v testdata.par2 > $TESTROOT/$testname.log || { echo "ERROR: Initial PAR 2.0 verification failed" ; exit 1; } >&2
+$execdir/par2 v testdata.par2 || { echo "ERROR: Initial PAR 2.0 verification failed" ; exit 1; } >&2
 
 cd $TESTROOT
 rm -rf run$testname
diff --git a/tests/test20 b/tests/test20
--- a/tests/test20
+++ b/tests/test20
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -35,7 +34,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 c -s1000 -c0 recovery myfile.dat > $TESTROOT/$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$execdir/par2 c -s1000 -c0 recovery myfile.dat || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 banner="split files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -56,7 +55,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 r recovery.par2 ./* >> $TESTROOT/$testname.log || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
+$execdir/par2 r recovery.par2 ./* || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
 
 cd $TESTROOT
 rm -rf run$testname
diff --git a/tests/test21 b/tests/test21
--- a/tests/test21
+++ b/tests/test21
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -39,7 +38,7 @@ echo $dashes
 cd datafiles
 tar -xzf $TESTDATA/flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
-$execdir/par2 c -B ./ ../parfiles/recovery * > $TESTROOT/$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$execdir/par2 c -B ./ ../parfiles/recovery * || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 banner="Verifying PAR 2.0 recovery data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -48,7 +47,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 v -B ./ ../parfiles/recovery.par2 >> $TESTROOT/$testname.log || { echo "ERROR: Verifying PAR 2.0 data failed" ; exit 1; } >&2
+$execdir/par2 v -B ./ ../parfiles/recovery.par2 || { echo "ERROR: Verifying PAR 2.0 data failed" ; exit 1; } >&2
 
 cd $TESTROOT
 rm -rf run$testname
diff --git a/tests/test26 b/tests/test26
--- a/tests/test26
+++ b/tests/test26
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -29,9 +28,9 @@ echo $dashes
 mkdir subfolder
 
 echo "file contents" > subfolder/some-file
-$execdir/par2 create `pwd`/subfolder/some-file > $TESTROOT/$testname.log || { echo "ERROR: Failed to create parchive"; exit1; } >&2
+$execdir/par2 create `pwd`/subfolder/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
 echo "corrupted contents" > subfolder/some-file
-$execdir/par2 repair subfolder/some-file >> $TESTROOT/$testname.log || { echo "ERROR: Failed to repair"; exit 1; } >&2
+$execdir/par2 repair subfolder/some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2
 
 cd $TESTROOT
 rm -rf run$testname
diff --git a/tests/test27 b/tests/test27
--- a/tests/test27
+++ b/tests/test27
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -32,9 +31,9 @@ ln -s folder/subfolder tmp
 cd tmp
 
 echo "file contents" > some-file
-$execdir/par2 create `pwd`/some-file > $TESTROOT/$testname.log || { echo "ERROR: Failed to create parchive"; exit1; } >&2
+$execdir/par2 create `pwd`/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
 echo "corrupted contents" > some-file
-$execdir/par2 repair some-file >> $TESTROOT/$testname.log || { echo "ERROR: Failed to repair"; exit 1; } >&2
+$execdir/par2 repair some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2
 
 cd $TESTROOT
 rm -rf run$testname
diff --git a/tests/test3 b/tests/test3
--- a/tests/test3
+++ b/tests/test3
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -41,7 +40,7 @@ echo $banner
 echo $dashes
 
 rm -f test-1.data test-3.data
-$execdir/par2 r testdata.par > $TESTROOT/$testname.log || { echo "ERROR: Reconstruction of two files using PAR 1.0 failed" ; exit 1; } >&2
+$execdir/par2 r testdata.par || { echo "ERROR: Reconstruction of two files using PAR 1.0 failed" ; exit 1; } >&2
 cmp -s test-1.data test-1.data.orig && cmp -s test-3.data test-3.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
 
 cd $TESTROOT
diff --git a/tests/test5 b/tests/test5
--- a/tests/test5
+++ b/tests/test5
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -28,7 +27,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 c -r100 -b190 -a newtest test-*.data > $TESTROOT/$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$execdir/par2 c -r100 -b190 -a newtest test-*.data || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 cp test-0.data test-0.data.orig
 cp test-1.data test-1.data.orig
@@ -52,7 +51,7 @@ echo $dashes
 
 rm -f test-*.data
 
-$execdir/par2 r newtest.par2 >> $TESTROOT/$testname.log || { echo "ERROR: Full Repair using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 r newtest.par2 || { echo "ERROR: Full Repair using PAR 2.0 failed" ; exit 1; } >&2
 
 cmp -s test-0.data test-0.data.orig && cmp -s test-1.data test-1.data.orig && cmp -s test-2.data test-2.data.orig && cmp -s test-3.data test-3.data.orig && cmp -s test-4.data test-4.data.orig && cmp -s test-5.data test-5.data.orig && cmp -s test-6.data test-6.data.orig && cmp -s test-7.data test-7.data.orig && cmp -s test-8.data test-8.data.orig && cmp -s test-9.data test-9.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1 ; } >&2
 
diff --git a/tests/test8 b/tests/test8
--- a/tests/test8
+++ b/tests/test8
@@ -10,7 +10,6 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
 TESTROOT=$PWD
 
 testname=$(basename $0)
@@ -32,7 +31,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 c -R testdata.par2 * > $TESTROOT/$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 c -R testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd ..
 mv source1 source2
@@ -46,7 +45,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 v testdata.par2 >> $TESTROOT/$testname.log || { echo "ERROR: verification of files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 v testdata.par2 || { echo "ERROR: verification of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd $TESTROOT
 rm -rf run$testname
