Fix test scripts to support whitespace in project path.
Fix test scripts to support whitespace in project path.

diff --git a/tests/test11 b/tests/test11
--- a/tests/test11
+++ b/tests/test11
@@ -10,7 +10,7 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-TESTROOT=$PWD
+TESTROOT="$PWD"
 
 testname=$(basename $0)
 rm -f "$testname.log"
@@ -18,7 +18,7 @@ rm -rf "run$testname"
 
 mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $TESTDATA/100blocks.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf "$TESTDATA/100blocks.tar.gz" || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
 banner="create par2files using 100 blocks"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -27,7 +27,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 c -b100 testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+"$execdir/par2" c -b100 testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 banner="repair 5% of 100 blocks par2files removing 3 files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -38,7 +38,7 @@ echo $dashes
 
 rm file file1 file3
 
-$execdir/par2 r testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+"$execdir/par2" r testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 banner="repair 5% of 100 blocks par2files removing 1 files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -49,10 +49,10 @@ echo $dashes
 
 rm file5
 
-$execdir/par2 r testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+"$execdir/par2" r testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
-cd $TESTROOT
-rm -rf run$testname
+cd "$TESTROOT"
+rm -rf "run$testname"
 
 exit 0;
 
diff --git a/tests/test15 b/tests/test15
--- a/tests/test15
+++ b/tests/test15
@@ -10,7 +10,7 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-TESTROOT=$PWD
+TESTROOT="$PWD"
 
 testname=$(basename $0)
 rm -f "$testname.log"
@@ -18,7 +18,7 @@ rm -rf "run$testname"
 
 mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $TESTDATA/par2-0.6.8-crash.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf "$TESTDATA/par2-0.6.8-crash.tar.gz" || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
 banner="repair files should succeed, (issue #35)"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -28,10 +28,10 @@ echo $banner
 echo $dashes
 
 cd par2-0.6.8-crash
-$execdir/par2 r pack-ea5f7f848340980493ed39f5b7173d956c680e43.par2 || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
+"$execdir/par2" r pack-ea5f7f848340980493ed39f5b7173d956c680e43.par2 || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
 
-cd $TESTROOT
-rm -rf run$testname
+cd "$TESTROOT"
+rm -rf "run$testname"
 
 exit 0;
 
diff --git a/tests/test18 b/tests/test18
--- a/tests/test18
+++ b/tests/test18
@@ -10,7 +10,7 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-TESTROOT=$PWD
+TESTROOT="$PWD"
 
 testname=$(basename $0)
 rm -f "$testname.log"
@@ -18,7 +18,7 @@ rm -rf "run$testname"
 
 mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-cp $TESTDATA/flatdata.tar.gz ./ || { echo "ERROR: Could not copy data test files" ; exit 1; } >&2
+cp "$TESTDATA/flatdata.tar.gz" ./ || { echo "ERROR: Could not copy data test files" ; exit 1; } >&2
 
 banner="Creating PAR 2.0 recovery data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -27,7 +27,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 c recovery flatdata.tar.gz || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+"$execdir/par2" c recovery flatdata.tar.gz || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 banner="Verifying using PAR 2.0 data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -40,10 +40,10 @@ mv flatdata.tar.gz flatdata.tar.gz-orig
 dd if=flatdata.tar.gz-orig bs=1983 count=1 of=flatdata.tar.gz
 rm -f flatdata.tar.gz-orig
 
-$execdir/par2 r recovery.par2 ./* || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
+"$execdir/par2" r recovery.par2 ./* || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
 
-cd $TESTROOT
-rm -rf run$testname
+cd "$TESTROOT"
+rm -rf "run$testname"
 
 exit 0;
 
diff --git a/tests/test21 b/tests/test21
--- a/tests/test21
+++ b/tests/test21
@@ -10,7 +10,7 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-TESTROOT=$PWD
+TESTROOT="$PWD"
 
 testname=$(basename $0)
 rm -f "$testname.log"
@@ -36,9 +36,9 @@ echo $banner
 echo $dashes
 
 cd datafiles
-tar -xzf $TESTDATA/flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf "$TESTDATA/flatdata.tar.gz" || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
-$execdir/par2 c -B ./ ../parfiles/recovery * || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+"$execdir/par2" c -B ./ ../parfiles/recovery * || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 banner="Verifying PAR 2.0 recovery data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -47,10 +47,10 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 v -B ./ ../parfiles/recovery.par2 || { echo "ERROR: Verifying PAR 2.0 data failed" ; exit 1; } >&2
+"$execdir/par2" v -B ./ ../parfiles/recovery.par2 || { echo "ERROR: Verifying PAR 2.0 data failed" ; exit 1; } >&2
 
-cd $TESTROOT
-rm -rf run$testname
+cd "$TESTROOT"
+rm -rf "run$testname"
 
 exit 0;
 
diff --git a/tests/test26 b/tests/test26
--- a/tests/test26
+++ b/tests/test26
@@ -10,7 +10,7 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-TESTROOT=$PWD
+TESTROOT="$PWD"
 
 testname=$(basename $0)
 rm -f "$testname.log"
@@ -28,12 +28,12 @@ echo $dashes
 mkdir subfolder
 
 echo "file contents" > subfolder/some-file
-$execdir/par2 create `pwd`/subfolder/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
+"$execdir/par2" create "$(pwd)"/subfolder/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
 echo "corrupted contents" > subfolder/some-file
-$execdir/par2 repair subfolder/some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2
+"$execdir/par2" repair subfolder/some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2
 
-cd $TESTROOT
-rm -rf run$testname
+cd "$TESTROOT"
+rm -rf "run$testname"
 
 exit 0;
 
diff --git a/tests/test27 b/tests/test27
--- a/tests/test27
+++ b/tests/test27
@@ -10,7 +10,7 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-TESTROOT=$PWD
+TESTROOT="$PWD"
 
 testname=$(basename $0)
 rm -f "$testname.log"
@@ -31,12 +31,12 @@ ln -s folder/subfolder tmp
 cd tmp
 
 echo "file contents" > some-file
-$execdir/par2 create `pwd`/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
+"$execdir/par2" create "$(pwd)"/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
 echo "corrupted contents" > some-file
-$execdir/par2 repair some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2
+"$execdir/par2" repair some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2
 
-cd $TESTROOT
-rm -rf run$testname
+cd "$TESTROOT"
+rm -rf "run$testname"
 
 exit 0;
 
diff --git a/tests/test8 b/tests/test8
--- a/tests/test8
+++ b/tests/test8
@@ -10,7 +10,7 @@ else
   TESTDATA="$srcdir/tests"
 fi
 
-TESTROOT=$PWD
+TESTROOT="$PWD"
 
 testname=$(basename $0)
 rm -f "$testname.log"
@@ -18,7 +18,7 @@ rm -rf "run$testname"
 
 mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $TESTDATA/subdirdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf "$TESTDATA/subdirdata.tar.gz" || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
 mkdir source1 && mv subdir1 subdir2 source1
 
@@ -31,7 +31,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 c -R testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+"$execdir/par2" c -R testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd ..
 mv source1 source2
@@ -45,10 +45,10 @@ echo $dashes
 echo $banner
 echo $dashes
 
-$execdir/par2 v testdata.par2 || { echo "ERROR: verification of files using PAR 2.0 failed" ; exit 1; } >&2
+"$execdir/par2" v testdata.par2 || { echo "ERROR: verification of files using PAR 2.0 failed" ; exit 1; } >&2
 
-cd $TESTROOT
-rm -rf run$testname
+cd "$TESTROOT"
+rm -rf "run$testname"
 
 exit 0;
 
