Revert "cleanup writing of tests logfiles" for #81.
This reverts commit 8da570ba70862b98ae75ac6955c6456f121abb1c.
    cleanup writing of tests logfiles
because it tries to write in $srcdir, which might be write-protected,
which is checked by "make distcheck".

Conflicts:
	tests/test16
        - fixed path to log file
	tests/test19

diff --git a/tests/test21 b/tests/test21
--- a/tests/test21
+++ b/tests/test21
@@ -29,7 +29,7 @@ echo $dashes
 cd datafiles
 tar -xzf $tests/flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
-../../../par2 c ../parfiles/recovery * > $tests/$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+../../../par2 c ../parfiles/recovery * > ../$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 banner="Verifying PAR 2.0 recovery data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -38,7 +38,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../../par2 v ../parfiles/recovery.par2 >> $tests/$testname.log || { echo "ERROR: Verifying PAR 2.0 data failed" ; exit 1; } >&2
+../../../par2 v ../parfiles/recovery.par2 > ../$testname.log || { echo "ERROR: Verifying PAR 2.0 data failed" ; exit 1; } >&2
 
 cd ../..
 rm -rf run$testname
