Test scripts now use .exe and wine, if exe exists

diff --git a/tests/test1 b/tests/test1
--- a/tests/test1
+++ b/tests/test1
@@ -2,6 +2,15 @@
 
 execdir="$PWD"
 
+# allow for windows testing on linux
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -28,7 +37,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" v testdata.par || { echo "ERROR: Initial PAR 1.0 verification failed" ; exit 1; } >&2
+$PARBINARY v testdata.par || { echo "ERROR: Initial PAR 1.0 verification failed" ; exit 1; } >&2
 
 cd "$TESTROOT"
 rm -rf "run$testname"
diff --git a/tests/test10 b/tests/test10
--- a/tests/test10
+++ b/tests/test10
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -31,7 +39,7 @@ echo $dashes
 cp subdir1/test-0.data ./test-0.data.orig
 rm -rf subdir1
 
-"$execdir/par2" r testdata.par2 || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY r testdata.par2 || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
 cmp -s subdir1/test-0.data test-0.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
 
 cd "$TESTROOT"
diff --git a/tests/test11 b/tests/test11
--- a/tests/test11
+++ b/tests/test11
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -27,7 +35,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" c -b100 testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY c -b100 testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 banner="repair 5% of 100 blocks par2files removing 3 files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -38,7 +46,7 @@ echo $dashes
 
 rm file file1 file3
 
-"$execdir/par2" r testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY r testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 banner="repair 5% of 100 blocks par2files removing 1 files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -49,7 +57,7 @@ echo $dashes
 
 rm file5
 
-"$execdir/par2" r testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY r testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd "$TESTROOT"
 rm -rf "run$testname"
diff --git a/tests/test14 b/tests/test14
--- a/tests/test14
+++ b/tests/test14
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -27,7 +35,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" c testdata.par2 *.data || { echo "ERROR: creating repair files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY c testdata.par2 *.data || { echo "ERROR: creating repair files using PAR 2.0 failed" ; exit 1; } >&2
 
 banner="repair files where 1 byte got removed at the beginning of a file"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -39,7 +47,7 @@ echo $dashes
 mv test-1.data test-1.data-correct
 tail -c 177173 test-1.data-correct > test-1.data
 
-"$execdir/par2" r testdata.par2 || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY r testdata.par2 || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd "$TESTROOT"
 rm -rf "run$testname"
diff --git a/tests/test15 b/tests/test15
--- a/tests/test15
+++ b/tests/test15
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -28,7 +36,7 @@ echo $banner
 echo $dashes
 
 cd par2-0.6.8-crash
-"$execdir/par2" r pack-ea5f7f848340980493ed39f5b7173d956c680e43.par2 || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY r pack-ea5f7f848340980493ed39f5b7173d956c680e43.par2 || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd "$TESTROOT"
 rm -rf "run$testname"
diff --git a/tests/test16 b/tests/test16
--- a/tests/test16
+++ b/tests/test16
@@ -7,6 +7,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -34,7 +42,7 @@ echo $dashes
 
 cd subdir1
 
-"$execdir/par2" c -r2 test.par2 *.data ../subdir2/*.data > $testname.log || { echo "ERROR: creating files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY c -r2 test.par2 *.data ../subdir2/*.data > $testname.log || { echo "ERROR: creating files using PAR 2.0 failed" ; exit 1; } >&2
 
 # check if there were ignored files
 grep 'Ignoring' "$testname.log" || { echo "ERROR: there were no files ignored"; exit 1; } >&2
diff --git a/tests/test17 b/tests/test17
--- a/tests/test17
+++ b/tests/test17
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -29,7 +37,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" r recovery.par2 || { echo "ERROR: reparation of files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY r recovery.par2 || { echo "ERROR: reparation of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd "$TESTROOT"
 rm -rf "run$testname"
diff --git a/tests/test18 b/tests/test18
--- a/tests/test18
+++ b/tests/test18
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -27,7 +35,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" c recovery flatdata.tar.gz || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$PARBINARY c recovery flatdata.tar.gz || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 banner="Verifying using PAR 2.0 data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -40,7 +48,7 @@ mv flatdata.tar.gz flatdata.tar.gz-orig
 dd if=flatdata.tar.gz-orig bs=1983 count=1 of=flatdata.tar.gz
 rm -f flatdata.tar.gz-orig
 
-"$execdir/par2" r recovery.par2 ./* || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
+$PARBINARY r recovery.par2 ./* || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
 
 cd "$TESTROOT"
 rm -rf "run$testname"
diff --git a/tests/test19 b/tests/test19
--- a/tests/test19
+++ b/tests/test19
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -35,7 +43,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" c -s200 -c1 recovery datafile || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$PARBINARY c -s200 -c1 recovery datafile || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 ls -l
 
 banner="Damaging data file (trim first 100 bytes)"
@@ -57,7 +65,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" r -N -S99 -vv recovery.par2 && { echo "ERROR: Repair should not be possible with skip leaway set to 99" ; exit 1; } >&2
+$PARBINARY r -N -S99 -vv recovery.par2 && { echo "ERROR: Repair should not be possible with skip leaway set to 99" ; exit 1; } >&2
 ls -l
 
 banner="Repairing using PAR 2.0 data (with skip leaway 100 - should succeed)"
@@ -67,7 +75,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" r -N -S100 -vv recovery.par2 || { echo "ERROR: Repair should be possible with skip leaway set to 100" ; exit 1; } >&2
+$PARBINARY r -N -S100 -vv recovery.par2 || { echo "ERROR: Repair should be possible with skip leaway set to 100" ; exit 1; } >&2
 ls -l
 
 cd "$TESTROOT"
diff --git a/tests/test20 b/tests/test20
--- a/tests/test20
+++ b/tests/test20
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -34,7 +42,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" c -s1000 -c0 recovery myfile.dat || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$PARBINARY c -s1000 -c0 recovery myfile.dat || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 banner="split files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -55,7 +63,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" r recovery.par2 ./* || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
+$PARBINARY r recovery.par2 ./* || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
 
 cd "$TESTROOT"
 rm -rf "run$testname"
diff --git a/tests/test21 b/tests/test21
--- a/tests/test21
+++ b/tests/test21
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -38,7 +46,7 @@ echo $dashes
 cd datafiles
 tar -xzf "$TESTDATA/flatdata.tar.gz" || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
-"$execdir/par2" c -B ./ ../parfiles/recovery * || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$PARBINARY c -B ./ ../parfiles/recovery * || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 banner="Verifying PAR 2.0 recovery data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -47,7 +55,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" v -B ./ ../parfiles/recovery.par2 || { echo "ERROR: Verifying PAR 2.0 data failed" ; exit 1; } >&2
+$PARBINARY v -B ./ ../parfiles/recovery.par2 || { echo "ERROR: Verifying PAR 2.0 data failed" ; exit 1; } >&2
 
 cd "$TESTROOT"
 rm -rf "run$testname"
diff --git a/tests/test22 b/tests/test22
--- a/tests/test22
+++ b/tests/test22
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -34,7 +42,7 @@ echo $dashes
 
 cd rundir
 
-"$execdir/par2" c -r2 -B"$faraway" "$faraway"/test.par2 "$faraway"/*.data || { echo "ERROR: create of PAR 2.0 files failed" ; exit 1; } >&2
+$PARBINARY c -r2 -B"$faraway" "$faraway"/test.par2 "$faraway"/*.data || { echo "ERROR: create of PAR 2.0 files failed" ; exit 1; } >&2
 
 cd "$TESTROOT"
 rm -rf "run$testname"
diff --git a/tests/test24 b/tests/test24
--- a/tests/test24
+++ b/tests/test24
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -47,7 +55,7 @@ echo $dashes
 cd rundir
 
 rm -f "$faraway"/test-1.data "$faraway"/test-3.data
-"$execdir/par2" r -B"$faraway" "$faraway"/testdata.par2  || { echo "ERROR: repair of PAR 2.0 files failed" ; exit 1; } >&2
+$PARBINARY r -B"$faraway" "$faraway"/testdata.par2  || { echo "ERROR: repair of PAR 2.0 files failed" ; exit 1; } >&2
 cmp -s "$faraway"/test-1.data "$faraway"/test-1.data.orig && cmp -s "$faraway"/test-3.data "$faraway"/test-3.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
 
 cd "$TESTROOT"
diff --git a/tests/test26 b/tests/test26
--- a/tests/test26
+++ b/tests/test26
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -28,9 +36,9 @@ echo $dashes
 mkdir subfolder
 
 echo "file contents" > subfolder/some-file
-"$execdir/par2" create "$(pwd)"/subfolder/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
+$PARBINARY create "$(pwd)"/subfolder/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
 echo "corrupted contents" > subfolder/some-file
-"$execdir/par2" repair subfolder/some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2
+$PARBINARY repair subfolder/some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2
 
 cd "$TESTROOT"
 rm -rf "run$testname"
diff --git a/tests/test3 b/tests/test3
--- a/tests/test3
+++ b/tests/test3
@@ -2,6 +2,15 @@
 
 execdir="$PWD"
 
+# allow for windows testing on linux
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -40,7 +49,7 @@ echo $banner
 echo $dashes
 
 rm -f test-1.data test-3.data
-"$execdir/par2" r testdata.par || { echo "ERROR: Reconstruction of two files using PAR 1.0 failed" ; exit 1; } >&2
+$PARBINARY r testdata.par || { echo "ERROR: Reconstruction of two files using PAR 1.0 failed" ; exit 1; } >&2
 cmp -s test-1.data test-1.data.orig && cmp -s test-3.data test-3.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
 
 cd "$TESTROOT"
diff --git a/tests/test5 b/tests/test5
--- a/tests/test5
+++ b/tests/test5
@@ -2,6 +2,15 @@
 
 execdir="$PWD"
 
+# allow for windows testing on linux
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -27,7 +36,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" c -r100 -b190 -a newtest test-*.data || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$PARBINARY c -r100 -b190 -a newtest test-*.data || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 cp test-0.data test-0.data.orig
 cp test-1.data test-1.data.orig
@@ -51,7 +60,7 @@ echo $dashes
 
 rm -f test-*.data
 
-"$execdir/par2" r newtest.par2 || { echo "ERROR: Full Repair using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY r newtest.par2 || { echo "ERROR: Full Repair using PAR 2.0 failed" ; exit 1; } >&2
 
 cmp -s test-0.data test-0.data.orig && cmp -s test-1.data test-1.data.orig && cmp -s test-2.data test-2.data.orig && cmp -s test-3.data test-3.data.orig && cmp -s test-4.data test-4.data.orig && cmp -s test-5.data test-5.data.orig && cmp -s test-6.data test-6.data.orig && cmp -s test-7.data test-7.data.orig && cmp -s test-8.data test-8.data.orig && cmp -s test-9.data test-9.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1 ; } >&2
 
diff --git a/tests/test5rk b/tests/test5rk
--- a/tests/test5rk
+++ b/tests/test5rk
@@ -9,6 +9,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -39,7 +47,7 @@ echo $dashes
 # we approximately (-rk1302).
 # To also test ISSUE-80 (https://github.com/Parchive/par2cmdline/issues/80)
 # we also use "-n2".
-"$execdir/par2" c -rk1302 -b190 -n2 -a newtest test-*.data || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$PARBINARY c -rk1302 -b190 -n2 -a newtest test-*.data || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 # Checking whether "-n2" worked by creating two newtest.vol*.par2 files
 # (and also tolerate newtest.VOL*.PAR2 as seen on Windows)
@@ -72,7 +80,7 @@ echo $dashes
 
 rm -f test-*.data
 
-"$execdir/par2" r newtest.par2 || { echo "ERROR: Full Repair using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY r newtest.par2 || { echo "ERROR: Full Repair using PAR 2.0 failed" ; exit 1; } >&2
 
 #    for f in test-*.data; do cmp "$f" "$f.orig" || { echo XXX; exit 1; }; done
 cmp -s test-0.data test-0.data.orig && cmp -s test-1.data test-1.data.orig && cmp -s test-2.data test-2.data.orig && cmp -s test-3.data test-3.data.orig && cmp -s test-4.data test-4.data.orig && cmp -s test-5.data test-5.data.orig && cmp -s test-6.data test-6.data.orig && cmp -s test-7.data test-7.data.orig && cmp -s test-8.data test-8.data.orig && cmp -s test-9.data test-9.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1 ; } >&2
diff --git a/tests/test6 b/tests/test6
--- a/tests/test6
+++ b/tests/test6
@@ -2,6 +2,15 @@
 
 execdir="$PWD"
 
+# allow for windows testing on linux
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -32,7 +41,7 @@ cp subdir1/test-2.data subdir1/test-2.data.orig
 cp subdir2/test-7.data subdir2/test-7.data.orig
 
 rm -f subdir1/test-2.data subdir2/test-7.data
-"$execdir/par2" r testdata.par2 || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY r testdata.par2 || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
 cmp -s subdir1/test-2.data subdir1/test-2.data.orig && cmp -s subdir2/test-7.data subdir2/test-7.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
 
 cd "$TESTROOT"
diff --git a/tests/test8 b/tests/test8
--- a/tests/test8
+++ b/tests/test8
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -31,7 +39,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" c -R testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY c -R testdata.par2 * || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd ..
 mv source1 source2
@@ -45,7 +53,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-"$execdir/par2" v testdata.par2 || { echo "ERROR: verification of files using PAR 2.0 failed" ; exit 1; } >&2
+$PARBINARY v testdata.par2 || { echo "ERROR: verification of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd "$TESTROOT"
 rm -rf "run$testname"
diff --git a/tests/test9 b/tests/test9
--- a/tests/test9
+++ b/tests/test9
@@ -2,6 +2,14 @@
 
 execdir="$PWD"
 
+if [ `which wine` != "" ] && [ -f "$execdir/par2.exe" ]
+then
+    PARBINARY="wine $execdir/par2.exe"
+else
+    PARBINARY="$execdir/par2"
+fi
+
+
 if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
   srcdir="$PWD"
   TESTDATA="$srcdir/tests"
@@ -38,7 +46,7 @@ mv test-7.data rename3
 mv test-8.data rename1
 mv test-9.data rename2
 
-"$execdir/par2" r testdata.par2 rename* || { echo "ERROR: Initial PAR 2.0 verification and rename failed" ; exit 1; } >&2
+$PARBINARY r testdata.par2 rename* || { echo "ERROR: Initial PAR 2.0 verification and rename failed" ; exit 1; } >&2
 test -e test-1.data ||  { echo "ERROR: rename failed" ; exit 1; } >&2
 test -e test-2.data ||  { echo "ERROR: rename failed" ; exit 1; } >&2
 test -e test-3.data ||  { echo "ERROR: rename failed" ; exit 1; } >&2
