make sure we get the correct behaviour in the 'bup' tests
Signed-off-by: BlackEagle <ike.devolder@gmail.com>

diff --git a/tests/test24 b/tests/test24
--- a/tests/test24
+++ b/tests/test24
@@ -1,15 +1,18 @@
 #!/bin/sh
 
-cd $(dirname $0)
+cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
+tests=$PWD
 
 testname=$(basename $0)
 rm -f $testname.log
+rm -rf run$testname
 
 mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-faraway='in/a/folder/far/far/away'
+faraway="$PWD/in/a/folder/far/far/away"
 
 mkdir -p "$faraway" || { echo "ERROR: Could not create fancy folder" ; exit 1; } >&2
+mkdir rundir
 
 tar -xf ../flatdata.tar.gz -C "$faraway" || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 tar -xf ../flatdata-par2files.tar.gz -C "$faraway" || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
@@ -32,8 +35,10 @@ echo $dashes
 echo $banner
 echo $dashes
 
+cd rundir
+
 rm -f "$faraway"/test-1.data "$faraway"/test-3.data
-../../par2 r "$faraway"/testdata.par2  > ../$testname.log || { echo "ERROR: repair of PAR 2.0 files failed" ; exit 1; } >&2
+../../../par2 r "$faraway"/testdata.par2  > ../$testname.log || { echo "ERROR: repair of PAR 2.0 files failed" ; exit 1; } >&2
 cmp -s "$faraway"/test-1.data "$faraway"/test-1.data.orig && cmp -s "$faraway"/test-3.data "$faraway"/test-3.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
 
 cd ..
