move tests in tests subfolder
Signed-off-by: BlackEagle <ike.devolder@gmail.com>

diff --git a/tests/test1 b/tests/test1
--- a/tests/test1
+++ b/tests/test1
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+cd $(dirname $0)
+
 cd testdir || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
 banner="Verifying using PAR 1.0 data"
@@ -9,7 +11,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../par2 v testdata.par > ../test1.log || { echo "ERROR: Initial PAR 1.0 verification failed" ; exit 1; } >&2
+../../par2 v testdata.par > ../test1.log || { echo "ERROR: Initial PAR 1.0 verification failed" ; exit 1; } >&2
 
 exit 0;
 
diff --git a/tests/test4 b/tests/test4
--- a/tests/test4
+++ b/tests/test4
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+cd $(dirname $0)
+
 cd testdir || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
 banner="Repairing two files using PAR 2.0 data"
@@ -10,7 +12,7 @@ echo $banner
 echo $dashes
 
 rm -f test-1.data test-3.data
-../par2 r testdata.par2 > ../test4.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
+../../par2 r testdata.par2 > ../test4.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
 cmp -s test-1.data test-1.data.orig && cmp -s test-3.data test-3.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
 
 exit 0;
diff --git a/tests/test5 b/tests/test5
--- a/tests/test5
+++ b/tests/test5
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+cd $(dirname $0)
+
 cd testdir || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
 banner="Creating 100% PAR 2.0 recovery data"
@@ -9,7 +11,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../par2 c -r100 -b190 -a newtest test-*.data > ../test5.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+../../par2 c -r100 -b190 -a newtest test-*.data > ../test5.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 exit 0;
 
diff --git a/tests/test8 b/tests/test8
--- a/tests/test8
+++ b/tests/test8
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+cd $(dirname $0)
+
 cd testdir/subdirwin || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
 banner="Repairing two files in subdirs using PAR 2.0 data generated on windows"
@@ -10,7 +12,7 @@ echo $banner
 echo $dashes
 
 rm -f subdir1/test-0.data
-../../par2 r testdata.par2 > ../test8.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
+../../../par2 r testdata.par2 > ../test8.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
 cmp -s subdir1/test-2.data ../test-2.data.orig && cmp -s subdir2/test-7.data ../test-7.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
 
 exit 0;
