enhanced tests to allow check, distcheck, ...
Added "default" folders to ease the use of the tests.
- execdir: where the tests are executed from, also contains the par2
  binary
- TESTDATA: where the tests are located with their data
- TESTROOT: where the tests are being run, where they store data during
  testing

Also improved some tests where the logs were constantly overwritten,
made the end phase uniform across tests, ...

Signed-off-by: BlackEagle <ike.devolder@gmail.com>

diff --git a/tests/test11 b/tests/test11
--- a/tests/test11
+++ b/tests/test11
@@ -1,15 +1,25 @@
 #!/bin/sh
 
+execdir="$PWD"
+
+if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
+  srcdir="$PWD"
+  TESTDATA="$srcdir/tests"
+else
+  srcdir="$PWD/$srcdir"
+  TESTDATA="$srcdir/tests"
+fi
+
 cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
-tests=../../$srcdir/tests
+TESTROOT=$PWD
 
 testname=$(basename $0)
-rm -f $testname.log
-rm -rf run$testname
+rm -f "$testname.log"
+rm -rf "run$testname"
 
-mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $tests/100blocks.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/100blocks.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
 banner="create par2files using 100 blocks"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -18,7 +28,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../par2 c -b100 testdata.par2 * > ../$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 c -b100 testdata.par2 * > $TESTROOT/$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 banner="repair 5% of 100 blocks par2files removing 3 files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -29,7 +39,7 @@ echo $dashes
 
 rm file file1 file3
 
-../../par2 r testdata.par2 * > ../$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 r testdata.par2 * >> $TESTROOT/$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 banner="repair 5% of 100 blocks par2files removing 1 files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -40,9 +50,9 @@ echo $dashes
 
 rm file5
 
-../../par2 r testdata.par2 * > ../$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 r testdata.par2 * > $TESTROOT/$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
-cd ..
+cd $TESTROOT
 rm -rf run$testname
 
 exit 0;
diff --git a/tests/test13 b/tests/test13
--- a/tests/test13
+++ b/tests/test13
@@ -1,15 +1,25 @@
 #!/bin/sh
 
+execdir="$PWD"
+
+if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
+  srcdir="$PWD"
+  TESTDATA="$srcdir/tests"
+else
+  srcdir="$PWD/$srcdir"
+  TESTDATA="$srcdir/tests"
+fi
+
 cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
-tests=../../$srcdir/tests
+TESTROOT=$PWD
 
 testname=$(basename $0)
-rm -f $testname.log
-rm -rf run$testname
+rm -f "$testname.log"
+rm -rf "run$testname"
 
-mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $tests/flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
 banner="create 5% recovery files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -18,7 +28,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../par2 c testdata.par2 *.data > ../$testname.log || { echo "ERROR: creating repair files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 c testdata.par2 *.data > $TESTROOT/$testname.log || { echo "ERROR: creating repair files using PAR 2.0 failed" ; exit 1; } >&2
 
 banner="repair files where 1 byte got removed at the end of a file"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -30,9 +40,9 @@ echo $dashes
 mv test-1.data test-1.data-correct
 dd if=test-1.data-correct bs=177173 count=1 of=test-1.data
 
-../../par2 r testdata.par2 > ../$testname.log || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 r testdata.par2 > $TESTROOT/$testname.log || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
 
-cd ..
+cd $TESTROOT
 rm -rf run$testname
 
 exit 0;
diff --git a/tests/test15 b/tests/test15
--- a/tests/test15
+++ b/tests/test15
@@ -1,15 +1,25 @@
 #!/bin/sh
 
+execdir="$PWD"
+
+if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
+  srcdir="$PWD"
+  TESTDATA="$srcdir/tests"
+else
+  srcdir="$PWD/$srcdir"
+  TESTDATA="$srcdir/tests"
+fi
+
 cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
-tests=../../$srcdir/tests
+TESTROOT=$PWD
 
 testname=$(basename $0)
-rm -f $testname.log
-rm -rf run$testname
+rm -f "$testname.log"
+rm -rf "run$testname"
 
-mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $tests/par2-0.6.8-crash.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/par2-0.6.8-crash.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
 banner="repair files should succeed, (issue #35)"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -19,9 +29,9 @@ echo $banner
 echo $dashes
 
 cd par2-0.6.8-crash
-../../../par2 r pack-ea5f7f848340980493ed39f5b7173d956c680e43.par2 > ../../$testname.log || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 r pack-ea5f7f848340980493ed39f5b7173d956c680e43.par2 > $TESTROOT/$testname.log || { echo "ERROR: repair files using PAR 2.0 failed" ; exit 1; } >&2
 
-cd ../..
+cd $TESTROOT
 rm -rf run$testname
 
 exit 0;
diff --git a/tests/test16 b/tests/test16
--- a/tests/test16
+++ b/tests/test16
@@ -5,16 +5,26 @@
 # basepath
 ######
 
+execdir="$PWD"
+
+if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
+  srcdir="$PWD"
+  TESTDATA="$srcdir/tests"
+else
+  srcdir="$PWD/$srcdir"
+  TESTDATA="$srcdir/tests"
+fi
+
 cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
-tests=../../$srcdir/tests
+TESTROOT=$PWD
 
 testname=$(basename $0)
-rm -f $testname.log
-rm -rf run$testname
+rm -f "$testname.log"
+rm -rf "run$testname"
 
-mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $tests/subdirdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/subdirdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
 banner="don't allow files outside par2 basedir, (issue #34, #36)"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -25,12 +35,12 @@ echo $dashes
 
 cd subdir1
 
-../../../par2 c -r2 test.par2 *.data ../subdir2/*.data > ../../$testname.log || { echo "ERROR: creating files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 c -r2 test.par2 *.data ../subdir2/*.data > $TESTROOT/$testname.log || { echo "ERROR: creating files using PAR 2.0 failed" ; exit 1; } >&2
 
 # check if there were ignored files
-grep 'Ignoring' ../../$testname.log || { echo "ERROR: there were no files ignored"; exit 1; } >&2
+grep 'Ignoring' $TESTROOT/$testname.log || { echo "ERROR: there were no files ignored"; exit 1; } >&2
 
-cd ../..
+cd $TESTROOT
 rm -rf run$testname
 
 exit 0;
diff --git a/tests/test20 b/tests/test20
--- a/tests/test20
+++ b/tests/test20
@@ -1,13 +1,23 @@
 #!/bin/sh
 
+execdir="$PWD"
+
+if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
+  srcdir="$PWD"
+  TESTDATA="$srcdir/tests"
+else
+  srcdir="$PWD/$srcdir"
+  TESTDATA="$srcdir/tests"
+fi
+
 cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
-tests=../../$srcdir/tests
+TESTROOT=$PWD
 
 testname=$(basename $0)
-rm -f $testname.log
-rm -rf run$testname
+rm -f "$testname.log"
+rm -rf "run$testname"
 
-mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
 banner="genereate datafile with 2000 random bytes"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -25,7 +35,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../par2 c -s1000 -c0 recovery myfile.dat > ../$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+$execdir/par2 c -s1000 -c0 recovery myfile.dat > $TESTROOT/$testname.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
 
 banner="split files"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -46,9 +56,9 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../par2 r recovery.par2 ./* > ../$testname.log || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
+$execdir/par2 r recovery.par2 ./* >> $TESTROOT/$testname.log || { echo "ERROR: PAR 2.0 repair failed" ; exit 1; } >&2
 
-cd ..
+cd $TESTROOT
 rm -rf run$testname
 
 exit 0;
diff --git a/tests/test26 b/tests/test26
--- a/tests/test26
+++ b/tests/test26
@@ -1,15 +1,23 @@
 #!/bin/sh
 
+execdir="$PWD"
+
+if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
+  srcdir="$PWD"
+  TESTDATA="$srcdir/tests"
+else
+  srcdir="$PWD/$srcdir"
+  TESTDATA="$srcdir/tests"
+fi
+
 cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
-# Unfortunately test object seems to need absolute path
 TESTROOT=$PWD
-tests=../../$srcdir/tests
 
 testname=$(basename $0)
-rm -f $testname.log
-rm -rf run$testname
+rm -f "$testname.log"
+rm -rf "run$testname"
 
-mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
 banner="par2 with full path and creation and repair in subfolder"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -21,11 +29,11 @@ echo $dashes
 mkdir subfolder
 
 echo "file contents" > subfolder/some-file
-../../par2 create `pwd`/subfolder/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
+$execdir/par2 create `pwd`/subfolder/some-file > $TESTROOT/$testname.log || { echo "ERROR: Failed to create parchive"; exit1; } >&2
 echo "corrupted contents" > subfolder/some-file
-../../par2 repair subfolder/some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2
+$execdir/par2 repair subfolder/some-file >> $TESTROOT/$testname.log || { echo "ERROR: Failed to repair"; exit 1; } >&2
 
-cd ..
+cd $TESTROOT
 rm -rf run$testname
 
 exit 0;
diff --git a/tests/test27 b/tests/test27
--- a/tests/test27
+++ b/tests/test27
@@ -1,16 +1,23 @@
 #!/bin/sh
 
-startdir="$PWD"
+execdir="$PWD"
+
+if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
+  srcdir="$PWD"
+  TESTDATA="$srcdir/tests"
+else
+  srcdir="$PWD/$srcdir"
+  TESTDATA="$srcdir/tests"
+fi
 
 cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
-# Unfortunately test object seems to need absolute path
-TESTROOT="$PWD"
+TESTROOT=$PWD
 
 testname=$(basename $0)
-rm -f $testname.log
-rm -rf run$testname
+rm -f "$testname.log"
+rm -rf "run$testname"
 
-mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
 banner="par2 with full path"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -19,18 +26,17 @@ echo $dashes
 echo $banner
 echo $dashes
 
-mkdir folder
-mkdir folder/subfolder
+mkdir -p folder/subfolder
 ln -s folder/subfolder tmp
 
 cd tmp
 
 echo "file contents" > some-file
-"$startdir"/par2 create `pwd`/some-file || { echo "ERROR: Failed to create parchive"; exit1; } >&2
+$execdir/par2 create `pwd`/some-file > $TESTROOT/$testname.log || { echo "ERROR: Failed to create parchive"; exit1; } >&2
 echo "corrupted contents" > some-file
-"$startdir"/par2 repair some-file || { echo "ERROR: Failed to repair"; exit 1; } >&2
+$execdir/par2 repair some-file >> $TESTROOT/$testname.log || { echo "ERROR: Failed to repair"; exit 1; } >&2
 
-cd ../..
+cd $TESTROOT
 rm -rf run$testname
 
 exit 0;
diff --git a/tests/test4 b/tests/test4
--- a/tests/test4
+++ b/tests/test4
@@ -1,16 +1,26 @@
 #!/bin/sh
 
+execdir="$PWD"
+
+if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
+  srcdir="$PWD"
+  TESTDATA="$srcdir/tests"
+else
+  srcdir="$PWD/$srcdir"
+  TESTDATA="$srcdir/tests"
+fi
+
 cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
-tests=../../$srcdir/tests
+TESTROOT=$PWD
 
 testname=$(basename $0)
-rm -f $testname.log
-rm -rf run$testname
+rm -f "$testname.log"
+rm -rf "run$testname"
 
-mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $tests/flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
-tar -xzf $tests/flatdata-par2files.tar.gz || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/flatdata-par2files.tar.gz || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2
 
 cp test-0.data test-0.data.orig
 cp test-1.data test-1.data.orig
@@ -31,10 +41,10 @@ echo $banner
 echo $dashes
 
 rm -f test-1.data test-3.data
-../../par2 r testdata.par2 > ../$testname.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 r testdata.par2 > $TESTROOT/$testname.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
 cmp -s test-1.data test-1.data.orig && cmp -s test-3.data test-3.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
 
-cd ..
+cd $TESTROOT
 rm -rf run$testname
 
 exit 0;
diff --git a/tests/test6 b/tests/test6
--- a/tests/test6
+++ b/tests/test6
@@ -1,16 +1,26 @@
 #!/bin/sh
 
+execdir="$PWD"
+
+if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
+  srcdir="$PWD"
+  TESTDATA="$srcdir/tests"
+else
+  srcdir="$PWD/$srcdir"
+  TESTDATA="$srcdir/tests"
+fi
+
 cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
-tests=../../$srcdir/tests
+TESTROOT=$PWD
 
 testname=$(basename $0)
-rm -f $testname.log
-rm -rf run$testname
+rm -f "$testname.log"
+rm -rf "run$testname"
 
-mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $tests/subdirdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
-tar -xzf $tests/subdirdata-par2files-unix.tar.gz || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/subdirdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/subdirdata-par2files-unix.tar.gz || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2
 
 banner="Repairing two files in subdirs using PAR 2.0 data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -23,10 +33,10 @@ cp subdir1/test-2.data subdir1/test-2.data.orig
 cp subdir2/test-7.data subdir2/test-7.data.orig
 
 rm -f subdir1/test-2.data subdir2/test-7.data
-../../par2 r testdata.par2 > ../$testname.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 r testdata.par2 > $TESTROOT/$testname.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
 cmp -s subdir1/test-2.data subdir1/test-2.data.orig && cmp -s subdir2/test-7.data subdir2/test-7.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
 
-cd ..
+cd $TESTROOT
 rm -rf run$testname
 
 exit 0;
diff --git a/tests/test8 b/tests/test8
--- a/tests/test8
+++ b/tests/test8
@@ -1,15 +1,25 @@
 #!/bin/sh
 
+execdir="$PWD"
+
+if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
+  srcdir="$PWD"
+  TESTDATA="$srcdir/tests"
+else
+  srcdir="$PWD/$srcdir"
+  TESTDATA="$srcdir/tests"
+fi
+
 cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
-tests=../../$srcdir/tests
+TESTROOT=$PWD
 
 testname=$(basename $0)
-rm -f $testname.log
-rm -rf run$testname
+rm -f "$testname.log"
+rm -rf "run$testname"
 
-mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $tests/subdirdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/subdirdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
 mkdir source1 && mv subdir1 subdir2 source1
 
@@ -22,7 +32,7 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../../par2 c -R testdata.par2 * > ../../$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 c -R testdata.par2 * > $TESTROOT/$testname.log || { echo "ERROR: construction of files using PAR 2.0 failed" ; exit 1; } >&2
 
 cd ..
 mv source1 source2
@@ -36,9 +46,9 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../../par2 v testdata.par2 >> ../../$testname.log || { echo "ERROR: verification of files using PAR 2.0 failed" ; exit 1; } >&2
+$execdir/par2 v testdata.par2 >> $TESTROOT/$testname.log || { echo "ERROR: verification of files using PAR 2.0 failed" ; exit 1; } >&2
 
-cd ../..
+cd $TESTROOT
 rm -rf run$testname
 
 exit 0;
diff --git a/tests/test9 b/tests/test9
--- a/tests/test9
+++ b/tests/test9
@@ -1,16 +1,26 @@
 #!/bin/sh
 
+execdir="$PWD"
+
+if [ -z "$srcdir" ] || [ "." = "$srcdir" ]; then
+  srcdir="$PWD"
+  TESTDATA="$srcdir/tests"
+else
+  srcdir="$PWD/$srcdir"
+  TESTDATA="$srcdir/tests"
+fi
+
 cd tests || { echo "ERROR: Could not change to tests directory" ; exit 1; } >&2
-tests=../../$srcdir/tests
+TESTROOT=$PWD
 
 testname=$(basename $0)
-rm -f $testname.log
-rm -rf run$testname
+rm -f "$testname.log"
+rm -rf "run$testname"
 
-mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+mkdir "run$testname" && cd "run$testname" || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
 
-tar -xzf $tests/flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
-tar -xzf $tests/flatdata-par2files.tar.gz || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xzf $TESTDATA/flatdata-par2files.tar.gz || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2
 
 banner="rename using PAR 2.0 data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -29,7 +39,7 @@ mv test-7.data rename3
 mv test-8.data rename1
 mv test-9.data rename2
 
-../../par2 r testdata.par2 rename* > ../$testname.log || { echo "ERROR: Initial PAR 2.0 verification and rename failed" ; exit 1; } >&2
+$execdir/par2 r testdata.par2 rename* > $TESTROOT/$testname.log || { echo "ERROR: Initial PAR 2.0 verification and rename failed" ; exit 1; } >&2
 test -e test-1.data ||  { echo "ERROR: rename failed" ; exit 1; } >&2
 test -e test-2.data ||  { echo "ERROR: rename failed" ; exit 1; } >&2
 test -e test-3.data ||  { echo "ERROR: rename failed" ; exit 1; } >&2
@@ -40,7 +50,7 @@ test -e test-7.data ||  { echo "ERROR: rename failed" ; exit 1; } >&2
 test -e test-8.data ||  { echo "ERROR: rename failed" ; exit 1; } >&2
 test -e test-9.data ||  { echo "ERROR: rename failed" ; exit 1; } >&2
 
-cd ..
+cd $TESTROOT
 rm -rf run$testname
 
 exit 0;
