rework tests, paralellization is possible now
Signed-off-by: BlackEagle <ike.devolder@gmail.com>

diff --git a/tests/test1 b/tests/test1
--- a/tests/test1
+++ b/tests/test1
@@ -2,7 +2,13 @@
 
 cd $(dirname $0)
 
-cd testdir || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+testname=$(basename $0)
+rm -f $testname.log
+
+mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+
+tar -xf ../flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xf ../flatdata-par1files.tar.gz || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2
 
 banner="Verifying using PAR 1.0 data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -11,7 +17,10 @@ echo $dashes
 echo $banner
 echo $dashes
 
-../../par2 v testdata.par > ../test1.log || { echo "ERROR: Initial PAR 1.0 verification failed" ; exit 1; } >&2
+../../par2 v testdata.par > ../$testname.log || { echo "ERROR: Initial PAR 1.0 verification failed" ; exit 1; } >&2
+
+cd ..
+rm -rf run$testname
 
 exit 0;
 
diff --git a/tests/test5 b/tests/test5
--- a/tests/test5
+++ b/tests/test5
@@ -2,7 +2,12 @@
 
 cd $(dirname $0)
 
-cd testdir || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+testname=$(basename $0)
+rm -f $testname.log
+
+mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+
+tar -xf ../flatdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
 
 banner="Creating 100% PAR 2.0 recovery data"
 dashes=`echo "$banner" | sed s/./-/g`
@@ -12,6 +17,35 @@ echo $banner
 echo $dashes
 
 ../../par2 c -r100 -b190 -a newtest test-*.data > ../test5.log || { echo "ERROR: Creating PAR 2.0 data failed" ; exit 1; } >&2
+
+cp test-0.data test-0.data.orig
+cp test-1.data test-1.data.orig
+cp test-2.data test-2.data.orig
+cp test-3.data test-3.data.orig
+cp test-4.data test-4.data.orig
+cp test-5.data test-5.data.orig
+cp test-6.data test-6.data.orig
+cp test-7.data test-7.data.orig
+cp test-8.data test-8.data.orig
+cp test-9.data test-9.data.orig
+
+rm -f test-*.data
+
+banner="Repairing 100% loss using PAR 2.0 data"
+dashes=`echo "$banner" | sed s/./-/g`
+
+echo $dashes
+echo $banner
+echo $dashes
+
+rm -f test-*.data
+
+../../par2 r newtest.par2 > ../$testname.log || { echo "ERROR: Full Repair using PAR 2.0 failed" ; exit 1; } >&2
+
+cmp -s test-0.data test-0.data.orig && cmp -s test-1.data test-1.data.orig && cmp -s test-2.data test-2.data.orig && cmp -s test-3.data test-3.data.orig && cmp -s test-4.data test-4.data.orig && cmp -s test-5.data test-5.data.orig && cmp -s test-6.data test-6.data.orig && cmp -s test-7.data test-7.data.orig && cmp -s test-8.data test-8.data.orig && cmp -s test-9.data test-9.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1 ; } >&2
+
+cd ..
+rm -rf run$testname
 
 exit 0;
 
diff --git a/tests/test6 b/tests/test6
--- a/tests/test6
+++ b/tests/test6
@@ -2,20 +2,30 @@
 
 cd $(dirname $0)
 
-cd testdir || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+testname=$(basename $0)
+rm -f $testname.log
 
-banner="Repairing 100% loss using PAR 2.0 data"
+mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+
+tar -xf ../subdirdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xf ../subdirdata-par2files-unix.tar.gz || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2
+
+banner="Repairing two files in subdirs using PAR 2.0 data"
 dashes=`echo "$banner" | sed s/./-/g`
 
 echo $dashes
 echo $banner
 echo $dashes
 
-rm -f test-*.data
+cp subdir1/test-2.data subdir1/test-2.data.orig
+cp subdir2/test-7.data subdir2/test-7.data.orig
 
-../../par2 r newtest.par2 > ../test6.log || { echo "ERROR: Full Repair using PAR 2.0 failed" ; exit 1; } >&2
+rm -f subdir1/test-2.data subdir2/test-7.data
+../../par2 r testdata.par2 > ../$testname.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
+cmp -s subdir1/test-2.data subdir1/test-2.data.orig && cmp -s subdir2/test-7.data subdir2/test-7.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
 
-cmp -s test-0.data test-0.data.orig && cmp -s test-1.data test-1.data.orig && cmp -s test-2.data test-2.data.orig && cmp -s test-3.data test-3.data.orig && cmp -s test-4.data test-4.data.orig && cmp -s test-5.data test-5.data.orig && cmp -s test-6.data test-6.data.orig && cmp -s test-7.data test-7.data.orig && cmp -s test-8.data test-8.data.orig && cmp -s test-9.data test-9.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1 ; } >&2
+cd ..
+rm -rf run$testname
 
 exit 0;
 
diff --git a/tests/test7 b/tests/test7
--- a/tests/test7
+++ b/tests/test7
@@ -2,18 +2,30 @@
 
 cd $(dirname $0)
 
-cd testdir/subdir || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+testname=$(basename $0)
+rm -f $testname.log
 
-banner="Repairing two files in subdirs using PAR 2.0 data"
+mkdir run$testname && cd run$testname || { echo "ERROR: Could not change to test directory" ; exit 1; } >&2
+
+tar -xf ../subdirdata.tar.gz || { echo "ERROR: Could not extract data test files" ; exit 1; } >&2
+tar -xf ../subdirdata-par2files-win.tar.gz || { echo "ERROR: Could not extract par test files" ; exit 1; } >&2
+
+banner="Repairing two files in subdirs using PAR 2.0 data generated on windows"
 dashes=`echo "$banner" | sed s/./-/g`
 
 echo $dashes
 echo $banner
 echo $dashes
 
+cp subdir1/test-2.data subdir1/test-2.data.orig
+cp subdir2/test-7.data subdir2/test-7.data.orig
+
 rm -f subdir1/test-2.data subdir2/test-7.data
-../../../par2 r testdata.par2 > ../test7.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
-cmp -s subdir1/test-2.data ../test-2.data.orig && cmp -s subdir2/test-7.data ../test-7.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
+../../par2 r testdata.par2 > ../$testname.log || { echo "ERROR: Reconstruction of two files using PAR 2.0 failed" ; exit 1; } >&2
+cmp -s subdir1/test-2.data subdir1/test-2.data.orig && cmp -s subdir2/test-7.data subdir2/test-7.data.orig || { echo "ERROR: Repaired files do not match originals" ; exit 1; } >&2
+
+cd ..
+rm -rf run$testname
 
 exit 0;
 
